name: config pipeline
on: [workflow_dispatch]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '[".github/sync.yml"]'
        env:
          BRANCH_NAME: ${{ github.ref_name }}
      - name: check file for debug
        run: cat .github/sync.yml